### ISSUE TITLE
Support for .jsbeautifyrc?

### ISSUE THREAD

**Issue by framerate** [vkadam/grunt-jsbeautifier#28]
If this is supported, I think the documentation is missing. Thanks!

**Comment by vkadam** [comment]
I have just completed the development of it. I too a slight different approach than discussed prior. Simple rule is if ".jsbeautifierrc" file exists use it instead of setting config value to true. [See this commit](https://github.com/vkadam/grunt-jsbeautifier/commit/d339341fcb36c014d609ebd5009f6607868e14ae).

**Comment by vkadam** [comment]
Release 0.2.8 published
