### ISSUE TITLE
Grunt 1.0.x support

### ISSUE THREAD

**Issue by lsuchanek** [vkadam/grunt-jsbeautifier#57]
The module fails to install with Grunt 1.0.x. Are there plans to bring support to the newest version? Thanks for all the hard work!

**Comment by emphaticsunshine** [comment]
I was able to get it working with Grunt 1.0.x. Are you sure it is failing because of this module? Can you post the error stack?

**Comment by alberto-chiesa** [comment]
AFAICT, the module works with the latest Grunt. The only issue is that the requirement is in the form

    "dependencies": {
        ...
        "grunt": "^0.4.1",
        ...
    }

I think it should be `">=0.4.1"`, because, as it is, it requires to download an obsolete (and useless) version of grunt just to please the dependency resolver. I don't need a version 0.4.5 (the last 0.x released) in my dependency tree.

Please fix this minor annoyance, and thank you much for this useful module!

**Comment by alberto-chiesa** [comment]
I submitted a Pull Request that hopefully fixes this issue: #58.

**Comment by evilaliv3** [comment]
i confirm the issue and the fix;

**Comment by evilaliv3** [comment]
for big projects is really important that this change is done in orer to move forward and adopt grunt 1.0.1

**Comment by vkadam** [comment]
Released 0.2.13, Thanks @alberto-chiesa for PR
